name: Build doc

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - 'master'  

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    # Standard drop-in approach that should work for most people.

    - name: Set up Python 3.9
      uses: actions/setup-python@v1
      with:
        python-version: 3.9

    - name: Get Python running
      run: |
        python -m pip install --user --upgrade --progress-bar off pip
        python -m pip install --user --upgrade --progress-bar off -r requirements.txt
        python -m pip install --user --upgrade --progress-bar off -r doc/requirements.txt
        python -m pip install --user --upgrade --progress-bar off ipython "https://api.github.com/repos/sphinx-gallery/sphinx-gallery/zipball/master" memory_profiler
        sudo apt install pandoc
        python -m pip install --user -e .
    # Look at what we have and fail early if there is some library conflict
    - name: Check installation
      run: |
        which python
        python -c "import coffeine"
        python -c "import pandoc"
    # Build docs
    - name: Generate HTML docs
      uses: rickstaa/sphinx-action@master
      with:
        docs-folder: "doc/"
    - uses: actions/upload-artifact@v2
      with:
        name: Documentation
        path: doc/_build/html/
